develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35736:35729"
  container_name: gfw-contribution-data-develop
  environment:
    NODE_ENV: dev
    QUEUE_URL: redis://192.168.99.100:6379
    QUEUE_PROVIDER: redis
    QUEUE_NAME: mail
    API_GATEWAY_URL: http://192.168.99.100:8000
    WRI_MAIL_RECIPIENTS: <mails>
  command: develop
  volumes:
    - ./app:/opt/gfw-contribution-data/app
